services:
  # De Angular Frontend
  frontend:
    container_name: gscience-ai-ui
    build: .
    ports:
      - "80:80" # Bezoek je app op http://localhost
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
