server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;
    include /etc/nginx/mime.types;

    # 1. Handle the Root (http://localhost/)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # 2. Handle the "Ghost" path (http://localhost/nl-BE/...)
    # This tells Nginx: "If they ask for /nl-BE/, look in the root folder instead"
    location /nl-BE/ {
        alias /usr/share/nginx/html/;
        try_files $uri $uri/ /index.html;
    }

       # implementation of health
       location /health {
          access_log off;
          add_header 'Content-Type' 'application/json';
          return 200 '{"status":"up"}';
        }
}